version: '3.8'
services:
  orchestrator:
    image: oleexo/rds/orchestrator
    build:
      context: ./
      dockerfile: ./src/app/Orchestrator/Dockerfile
    ports:
      - "5184:8000"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Aws__Region=http://localstack:4566"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 400m
    healthcheck:
      test: curl --fail http://localhost:8000/healthz/ready || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  # Localstack
  localstack:
    image: localstack/localstack-full:latest
    container_name: rds-localstack
    environment:
      - SERVICES=sns,sqs,dynamodb
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_CBOR_DISABLE=1
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    volumes:
      #      - localstack-data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  