global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: store
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:5282'
  - job_name: orchestrator
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:5184'
  - job_name: distributor
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:5271'
