{
 "title": "Services info",
 "description": "Dashboard to follow asp.net core services",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job!=\"services\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "The duration of HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "GC collection count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total[$interval])",
     "legendFormat": "{{job}} Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job!=\"services\"} / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}